/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bida.shop.ui;

import bida.shop.dao.NhanVienDAO;
import bida.shop.entity.User;
import bida.shop.ui.manager.DoiMatKhauJDialog;
import bida.shop.ui.manager.QuanLyBanJDialog;
import bida.shop.ui.manager.QuanLyDoUongJDialog;
import bida.shop.ui.manager.QuanLyDoanhThuJDialog;
import bida.shop.ui.manager.QuanLyNhanVienForm;
import bida.shop.ui.manager.ThayDoiGiaGioJDialog;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Main
     */
    
    Color DefaultColor, ClickedColor;
    
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        DefaultColor = new Color(89, 168, 105);
        ClickedColor = new Color(26, 188, 156);
        //String username = "nva"; // hoặc lấy từ form đăng nhập
        hienThiThongTinNhanVien();
    }
    
    private void hienThiThongTinNhanVien() {
    User nv = database.UserSession.currentUser;
    if (nv != null) {
        lblTenNV.setText(nv.getTenNv());
        lblVaiTro.setText(nv.getVaiTro());
    } else {
        lblTenNV.setText("Không đăng nhập");
        lblVaiTro.setText("");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCaChoi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlGhiNhanDoUong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlDoUong = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlGiaGio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlDoanhThu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlDoiMatKhau = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlDangXuat = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pnlMain = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bida Shop");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 202, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBan.setBackground(new java.awt.Color(48, 202, 150));
        pnlBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBanMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ban.png"))); // NOI18N
        jLabel1.setText("BÀN");

        javax.swing.GroupLayout pnlBanLayout = new javax.swing.GroupLayout(pnlBan);
        pnlBan.setLayout(pnlBanLayout);
        pnlBanLayout.setHorizontalGroup(
            pnlBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        pnlBanLayout.setVerticalGroup(
            pnlBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBanLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(pnlBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 40));

        pnlCaChoi.setBackground(new java.awt.Color(48, 202, 150));
        pnlCaChoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCaChoiMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cachoi.png"))); // NOI18N
        jLabel2.setText("CA CHƠI");

        javax.swing.GroupLayout pnlCaChoiLayout = new javax.swing.GroupLayout(pnlCaChoi);
        pnlCaChoi.setLayout(pnlCaChoiLayout);
        pnlCaChoiLayout.setHorizontalGroup(
            pnlCaChoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaChoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        pnlCaChoiLayout.setVerticalGroup(
            pnlCaChoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCaChoiLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(pnlCaChoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, -1));

        pnlNhanVien.setBackground(new java.awt.Color(48, 202, 150));
        pnlNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNhanVienMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nhanvien.png"))); // NOI18N
        jLabel4.setText("NHÂN VIÊN");

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanVienLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel1.add(pnlNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 40));

        pnlGhiNhanDoUong.setBackground(new java.awt.Color(48, 202, 150));
        pnlGhiNhanDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlGhiNhanDoUongMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(48, 202, 150));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ghinhandouong.png"))); // NOI18N
        jLabel3.setText("GHI NHẬN ĐỒ UỐNG");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlGhiNhanDoUongLayout = new javax.swing.GroupLayout(pnlGhiNhanDoUong);
        pnlGhiNhanDoUong.setLayout(pnlGhiNhanDoUongLayout);
        pnlGhiNhanDoUongLayout.setHorizontalGroup(
            pnlGhiNhanDoUongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGhiNhanDoUongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlGhiNhanDoUongLayout.setVerticalGroup(
            pnlGhiNhanDoUongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGhiNhanDoUongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(pnlGhiNhanDoUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 40));

        pnlDoUong.setBackground(new java.awt.Color(48, 202, 150));
        pnlDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDoUongMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/douong.png"))); // NOI18N
        jLabel6.setText("ĐỒ UỐNG");

        javax.swing.GroupLayout pnlDoUongLayout = new javax.swing.GroupLayout(pnlDoUong);
        pnlDoUong.setLayout(pnlDoUongLayout);
        pnlDoUongLayout.setHorizontalGroup(
            pnlDoUongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoUongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pnlDoUongLayout.setVerticalGroup(
            pnlDoUongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDoUongLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel1.add(pnlDoUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, -1));

        pnlGiaGio.setBackground(new java.awt.Color(48, 202, 150));
        pnlGiaGio.setForeground(new java.awt.Color(255, 255, 255));
        pnlGiaGio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlGiaGioMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/giagio.png"))); // NOI18N
        jLabel5.setText("GIÁ GIỜ");

        javax.swing.GroupLayout pnlGiaGioLayout = new javax.swing.GroupLayout(pnlGiaGio);
        pnlGiaGio.setLayout(pnlGiaGioLayout);
        pnlGiaGioLayout.setHorizontalGroup(
            pnlGiaGioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaGioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        pnlGiaGioLayout.setVerticalGroup(
            pnlGiaGioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaGioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(pnlGiaGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 220, -1));

        pnlDoanhThu.setBackground(new java.awt.Color(48, 202, 150));
        pnlDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDoanhThuMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/doanhthu.png"))); // NOI18N
        jLabel7.setText("DOANH THU");

        javax.swing.GroupLayout pnlDoanhThuLayout = new javax.swing.GroupLayout(pnlDoanhThu);
        pnlDoanhThu.setLayout(pnlDoanhThuLayout);
        pnlDoanhThuLayout.setHorizontalGroup(
            pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlDoanhThuLayout.setVerticalGroup(
            pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(pnlDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 220, -1));

        pnlDoiMatKhau.setBackground(new java.awt.Color(48, 202, 150));
        pnlDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDoiMatKhauMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/doimatkhau.png"))); // NOI18N
        jLabel9.setText("ĐỔI MẬT KHẨU");

        javax.swing.GroupLayout pnlDoiMatKhauLayout = new javax.swing.GroupLayout(pnlDoiMatKhau);
        pnlDoiMatKhau.setLayout(pnlDoiMatKhauLayout);
        pnlDoiMatKhauLayout.setHorizontalGroup(
            pnlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDoiMatKhauLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(23, 23, 23))
        );
        pnlDoiMatKhauLayout.setVerticalGroup(
            pnlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoiMatKhauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(pnlDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 220, -1));

        pnlDangXuat.setBackground(new java.awt.Color(48, 202, 150));
        pnlDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDangXuatMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dangxuat.png"))); // NOI18N
        jLabel10.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout pnlDangXuatLayout = new javax.swing.GroupLayout(pnlDangXuat);
        pnlDangXuat.setLayout(pnlDangXuatLayout);
        pnlDangXuatLayout.setHorizontalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDangXuatLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel10)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlDangXuatLayout.setVerticalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 220, -1));

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenNV.setText("Nguyễn Văn A");
        jPanel1.add(lblTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblVaiTro.setText("Quản lý");
        jPanel1.add(lblVaiTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 423, 220, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 570));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shop.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 860, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_pnlBanMouseClicked

    private void pnlBanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanMousePressed
        // TODO add your handling code here:
       pnlMain.removeAll();
        QuanLyBanJDialog ban = new QuanLyBanJDialog();
        pnlMain.add(ban).setVisible(true);
    }//GEN-LAST:event_pnlBanMousePressed

    private void pnlCaChoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCaChoiMousePressed
        // TODO add your handling code here:
        pnlMain.removeAll();
        CaChoiForm caChoi = new CaChoiForm();
        pnlMain.add(caChoi).setVisible(true);
    }//GEN-LAST:event_pnlCaChoiMousePressed

    private void pnlNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMousePressed
        // TODO add your handling code here:
        pnlMain.removeAll();
        QuanLyNhanVienForm nhanVien = new QuanLyNhanVienForm();
        pnlMain.add(nhanVien).setVisible(true);
    }//GEN-LAST:event_pnlNhanVienMousePressed

    private void pnlDoUongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoUongMousePressed
        // TODO add your handling code here:
        pnlMain.removeAll();
        QuanLyDoUongJDialog doUong = new QuanLyDoUongJDialog();
        pnlMain.add(doUong).setVisible(true);
    }//GEN-LAST:event_pnlDoUongMousePressed

    private void pnlGhiNhanDoUongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGhiNhanDoUongMousePressed
        // TODO add your handling code here:
        pnlMain.removeAll();
        GhiNhanDoUongForm ghiNhanDoUong = new GhiNhanDoUongForm();
        pnlMain.add(ghiNhanDoUong).setVisible(true);
    }//GEN-LAST:event_pnlGhiNhanDoUongMousePressed

    private void pnlDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMousePressed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(
                    null,
                    "Bạn có chắc chắn muốn đăng xuất?",
                    "Đăng xuất",
                    JOptionPane.YES_NO_OPTION
            );

            if (result == JOptionPane.YES_OPTION) {
                dispose(); // Đóng giao diện hiện tại

                // Mở lại giao diện đăng nhập
                new LoginJDialog().setVisible(true);
        }
    }//GEN-LAST:event_pnlDangXuatMousePressed

    private void pnlGiaGioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGiaGioMousePressed
        // TODO add your handling code here:
        pnlMain.removeAll();
        ThayDoiGiaGioJDialog thayDoiGiaGio = new ThayDoiGiaGioJDialog();
        pnlMain.add(thayDoiGiaGio).setVisible(true);
    }//GEN-LAST:event_pnlGiaGioMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        pnlMain.removeAll();
        GhiNhanDoUongForm ghiNhanDoUong = new GhiNhanDoUongForm();
        pnlMain.add(ghiNhanDoUong).setVisible(true);
    }//GEN-LAST:event_jLabel3MousePressed

    private void pnlDoanhThuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoanhThuMousePressed
        // TODO add your handling code here:
        pnlMain.removeAll();
        QuanLyDoanhThuJDialog quanLyDoanhThu = new QuanLyDoanhThuJDialog();
        pnlMain.add(quanLyDoanhThu).setVisible(true);
    }//GEN-LAST:event_pnlDoanhThuMousePressed

    private void pnlDoiMatKhauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoiMatKhauMousePressed
        // TODO add your handling code here:
        pnlMain.removeAll();
        DoiMatKhauJDialog doiMatKhau = new DoiMatKhauJDialog();
        pnlMain.add(doiMatKhau).setVisible(true);
    }//GEN-LAST:event_pnlDoiMatKhauMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JPanel pnlBan;
    private javax.swing.JPanel pnlCaChoi;
    private javax.swing.JPanel pnlDangXuat;
    private javax.swing.JPanel pnlDoUong;
    private javax.swing.JPanel pnlDoanhThu;
    private javax.swing.JPanel pnlDoiMatKhau;
    private javax.swing.JPanel pnlGhiNhanDoUong;
    private javax.swing.JPanel pnlGiaGio;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNhanVien;
    // End of variables declaration//GEN-END:variables
}
